version: '3.8'

services:

  syncronizer:
    build:
      context: .
      dockerfile: .docker/sync.dockerfile
    image: dojot-migration-tool:latest
    env_file:
      - vars.env
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: dojot/postgres:9.4.24-alpine
    restart: always
    env_file:
      - .env.source
      - .env.target
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./dumps:/tmp
    logging:
      driver: json-file

  mongodb:
    image: dojot/mongo:3.2
    restart: always
    volumes:
      - ./dumps:/tmp/dumps
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '5'   

volumes:
  dumps-volume:
  node_modules: