#!/bin/bash
echo "Starting restore proccess..."
docker-compose exec postgres sh -c "PGPASSWORD='postgres' psql -h 10.128.0.4 -U postgres -c 'drop database dojot_auth_043'"
docker-compose exec postgres sh -c "PGPASSWORD='postgres' psql -h 10.128.0.4 -U postgres -c 'create database dojot_auth_043'"
docker-compose exec postgres sh -c "PGPASSWORD='postgres' pg_restore -c -h 10.128.0.4 -U postgres -d dojot_auth_043 /tmp/dojot_auth.sql"
echo "Postgres: dojot_auth database has been restored"
docker-compose exec postgres sh -c "PGPASSWORD='postgres' pg_restore -c --role devm -h 10.128.0.4 -U postgres -d dojot_devm /tmp/dojot_devm.sql"
echo "Postgres: dojot_devm database has been dumped"
docker-compose exec postgres sh -c "PGPASSWORD='postgres' pg_restore -c --role imgm -h 10.128.0.4 -U postgres -d dojot_imgm /tmp/dojot_imgm.sql"
echo "Postgres: dojot_imgm database dumped"
docker-compose exec mongodb sh -c "mongorestore --quiet --host=10.128.0.4 --port=27017 /tmp/dumps"
# echo "MongoDB: all database dumped"   
echo "Restore proccess finished!"